### ISSUE TITLE
Plans to merge any waiting PRs?

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/aalto-boss-feedstock#21]
### Comment:

@jan-janssen There are currently PRs open for newer versions of this package, and the current max conda version (1.9.0) constrains numpy <=1.23.5, whereas [newer versions of this package](https://gitlab.com/cest-group/boss/-/blob/1.9.1/setup.py) lift that restriction.

**Comment by jan-janssen** [comment]
The current issue is that the new version requires `gpy >=1.13.1` which is not available on conda-forge. We are waiting for https://github.com/conda-forge/gpy-feedstock/pull/36 
```
Encountered problems while solving:
  - nothing provides requested gpy >=1.13.1
```

**Comment by jan-janssen** [comment]
They are merged now.
